# ─── Database (MySQL) ─────────────────────────────────────────────────────────
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/apargo_storage_mysql}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:meenagaming12@#}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:true}