# ─── Service Discovery ────────────────────────────────────────────────────────
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8888/eureka/}
    register-with-eureka: true
    fetch-registry: true
    enabled: ${EUREKA_ENABLED:false}

# ─── External Service URLs ───────────────────────────────────────────────────

user-service:
  base-url: ${USER_SERVICE_URL:http://localhost:7999}
  api-version: v1
  outgoing-enabled: true

waba-service:
  base-url: ${WABA_SERVICE_URL:http://localhost:8001}
  outgoing-enabled: true

whatsapp-service:
  api-version: ${FB_API_VERSION:v23.0}
  base-url: ${FB_GRAPH_URL:https://graph.facebook.com}
  outgoing-enabled: true